### ISSUE TITLE
`si_signo=Segmentation fault(11), si_code=1, si_addr=0x33445566` when running on ARM (Raspbian Linux)

### ISSUE THREAD

**Issue by esbenvb** [haraldkubota/l2-ethernet#1]
I'm running  this on a Raspberry Pi 4 and have installed the dart SDK and built this project.
I have also run the `buildme.sh` to make a `libeth.so` file available for `armv7l `. 

The `eth0` interface has no IP assigned. But I get this on every run.

```
pi@raspberrypi:~/l2-ethernet $ ./send_packet.exe
Preparing buffer of 100 bytes
Opening the socket
FYI: open() returned 8

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x33445566
Aborted

```

I get the same error when running the `colorlight.exe` or `loadimg.exe`, no matter if I use `root` or a limited user.

What can I do to fix this?

```
pi@raspberrypi:~/colorlight $ uname -a
Linux raspberrypi 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux
pi@raspberrypi:~/l2-ethernet $ dart --version
Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "linux_arm"
```

**Comment by esbenvb** [comment]
This seems to work on ARM64/ARMv8 (aarch64) based raspberry pi distros so I'll stick to this for now

**Comment by haraldkubota** [comment]
I have indeed not tested this on 32 bit ARM, but it's good to know that that this does not work on that architecture.
I'll make a corresponding note in the README.md
